version: '3.8'

services:
  db:
    image: mysql:8.0
    volumes:
      - mysql_data:/var/lib/mysql
    restart: always
    environment:
      MYSQL_DATABASE: 'fiction_db'
      MYSQL_USER: 'fiction_user'
      MYSQL_PASSWORD: '1234'
      MYSQL_ROOT_PASSWORD: 'rootpassword'
    ports:
      - "3306:3306"

  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      DB_NAME: 'fiction_db'
      DB_USER: 'fiction_user'
      DB_PASSWORD: '1234'
      DB_HOST: 'db'
      DB_PORT: '3306'

volumes:
  mysql_data:
